((nil . ((indent-tabs-mode . nil)
	 (tab-width . 8)
	 (fill-column . 92)
	 (ispell-local-dictionary . "american")))
 (julia-mode . ((tab-width . 8)
                (indent-tabs-mode . nil)
                (julia-indent-offset . 4)
                (fill-column . 92)))
 (makefile-gmake-mode . ((indent-tabs-mode . t)))
 (sh-mode . ((sh-basic-offset . 4)))
 )
