language: julia

os:
  - linux
  - osx

julia:
  - 1.3
  - 1
  - nightly

notifications:
  email: false

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.build("XPA"); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
