name = "XPA"
uuid = "d310a076-6a08-52b6-ab78-79baa254182b"
repo = "https://github.com/JuliaAstro/XPA.jl.git"
version = "0.2.1"

[deps]
XPA_jll = "9dbca590-e19a-5566-89a8-3997bfd21c58"

[compat]
julia = "1.3"
XPA_jll = "2.1.20"
