name: CI

on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ['lts', '1', 'min']
        # aarch64 for macOS only and the matrix options are fiddly and annoying
        arch: [x64, x86, aarch64]
        exclude:
          - os: ubunutu-latest
            version: aarch64
          - os: windows-latest
            version: aarch64
          - os: macos-latest
            arch: x86
          - os: macos-latest
            arch: x64

    steps:
      - uses: actions/checkout@v6
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v7
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
